### ISSUE TITLE
$util.map.copyAndRemoveAllKeys is not working

### ISSUE THREAD

**Issue by yukitaka13-1110** [bboure/serverless-appsync-simulator#106]
I'm developing appsync with serverless-framewrok.
I use dynamodb so I implemented vtl resolver files.
But `copyAndRemoveAllKeys` is not working.

See the following example code.
This is a `respose.vtl` code.

```vtl
#if($ctx.error)
    $util.error($ctx.error.message, $ctx.error.type)
#end
#set($messages = $ctx.result.items)
#set($mergedMessages = [])
#set($users = $ctx.prev.result.items)
#foreach($m in $messages)
  #set($uid = $m.uid)
  #foreach($user in $users)
    #if($uid == $user.id)
      #set($m = $util.map.copyAndRemoveAllKeys($m, ["uid"])) ## This line.
      $util.qr($m.put("user", $user))
      $util.qr($mergedMessages.add($m))
      #break
    #end
  #end
#end
#set($result = { "items": $mergedMessages })
$util.toJson($result)
```

This always returns null and no error occurred.
I deployed this code and query it.
Unfortunately, I could retrieve expected response, not null.

`query`
```graphql
query MyQuery {
  listChatMessages(groupId: "group-001") {
    items {
      id
      postDate
      user {
        color
        groupId
        id
      }
    }
  }
}

```

#### AppSync console result
```json
{
  "data": {
    "listChatMessages": {
      "items": [
        {
          "id": "group-001",
          "postDate": "2021-06-23T01:00:01Z",
          "user": {
            "color": "blue",
            "groupId": "group-001",
            "id": "user-001"
          }
        },
        {
          "id": "group-001",
          "postDate": "2021-06-23T01:02:01Z",
          "user": {
            "color": "red",
            "groupId": "group-001",
            "id": "user-002"
          }
        }
      ]
    }
  }
}
```

#### Local AppSync Simulator
```json
{
  "data": {
    "listChatMessages": null
  }
}
```

Is this bug?

#### Environment
```json
"dependencies": {
    "serverless-appsync-plugin": "^1.11.3",
    "serverless-appsync-simulator": "^0.17.0",
    "serverless-dynamodb-local": "^0.2.39",
    "serverless-offline": "^7.0.0",
    "webpack": "^5.40.0",
    "webpack-cli": "^4.7.2",
    "webpack-node-externals": "^3.0.0"
  }
```

**Comment by bboure** [comment]
@yukitaka13-1110 This is a known issue in [amplify-cli](https://github.com/aws-amplify/amplify-cli)

I have noticed it too and haven't had time to fix it. 
 a PR/issue should be opened in amplify-cli.

It happens because `["uid"]` is not transformed into a [JavaArray](https://github.com/aws-amplify/amplify-cli/blob/master/packages/amplify-appsync-simulator/src/velocity/value-mapper/array.ts)

In the meantime, here is the workaround I use:

```
#set($remove=["uid"])
#set($m = $util.map.copyAndRemoveAllKeys($m, $remove)) ## This line.
```

**Comment by yukitaka13-1110** [comment]
@bboure Thank you for your response!
I'll try it.

Additionally, I found `$HashMap.size()` is not working with the following error.

```
Error: Missing request mapping template.
```

Do you have any idea about this?

**Comment by yukitaka13-1110** [comment]
@bboure I confirmed my code worked correctly in AppSync console query.

**Comment by yukitaka13-1110** [comment]
@bboure Sample code.

```vtl
#set($obj = {})
#set($count = -1)

#set($count = $obj.size())
```
Local simulator: Missing request mapping template errror
AppSync Console: no error

**Comment by bboure** [comment]
Thanks @yukitaka13-1110 
Is that the full template? If so, it resolves to an empty template. I am not sure un what case that would happen? (maybe in pipelines??)

I know by experience that empty templates don't work, but I thought it was an AppSync, not simulator.
Templates should usually be JSON parsable. If the template does not return anything, I usually return `{}`

I will have a try at this. In any case, that would also be an issue in `amplify-cli` that we could fix there.

**Comment by yukitaka13-1110** [comment]
@bboure I found node version v16.0.0 caused this error.
Change to v12.0.0 then error disappeared but `size()` !== actual.

See this.

```vtl
#set($records = [
  { "id": "id-001"},
  { "id": "id-002"},
  { "id": "id-001"},
  { "id": "id-002"},
])

#set($obj = {})
#foreach($record in $records)
    #if($util.isNull($obj[$record.id]))
        $util.qr($obj.put($record.id, 1))
    #else
        #set($count = $obj[$record.id] + 1)
        $util.qr($obj.put($record.id, $count))
    #end
#end

## $obj.size() -> 4 but actual 2
```

I think this occurs when put same key twice.

```vtl
#set($records = [
  { "id": "id-001"},
  { "id": "id-002"},
])

#set($obj = {})
#foreach($record in $records)
    #if($util.isNull($obj[$record.id]))
        $util.qr($obj.put($record.id, 1))
    #else
        #set($count = $obj[$record.id] + 1)
        $util.qr($obj.put($record.id, $count))
    #end
#end

## $obj.size() -> 2 actual 2
```

**Comment by yukitaka13-1110** [comment]
@bboure In AppSync console, I got expected result.

```vtl
#set($records = [
  { "id": "id-001"},
  { "id": "id-002"},
  { "id": "id-001"},
  { "id": "id-002"}
])

#set($obj = {})
#foreach($record in $records)
    #if($util.isNull($obj[$record.id]))
        $util.qr($obj.put($record.id, 1))
    #else
        #set($count = $obj[$record.id] + 1)
        $util.qr($obj.put($record.id, $count))
    #end
#end
#set($count = $obj.size())
#set($result = { "obj": $obj, "count": $count })
$util.error($util.toJson($result), "debug")
```

```
"{\"obj\":{\"id-001\":2,\"id-002\":2},\"count\":2}
```
