### ISSUE TITLE
v0.17 breaks the hotreload (lambdas changes are ignored)

### ISSUE THREAD

**Issue by somq** [bboure/serverless-appsync-simulator#122]
**Describe the bug**
Starting at [`v0.17.0`](https://github.com/bboure/serverless-appsync-simulator/issues/74) the hot-reload feature gets broken, changes are ignored.

**To Reproduce**
Setup a template with webpack build to a custom folder, and set this custom folder as an `appsync-simulator` location.  

**Expected behavior**
Hotreload should take lambda changes into account, even with a custom location path.

**Additional context**
The lambda execution context does not seem to be passed anymore (`location` & `loadLocalEnv`) when executing a direct Axios request against the offline endpoint instead of using the [amplify `invoke` util](https://github.com/aws-amplify/amplify-cli/tree/master/packages/amplify-nodejs-function-runtime-provider).

**Comment by bboure** [comment]
Thank you @somq for reporting this.

I haven't had this issue.
Hot reloading for Lambda are handled by `serverless-offline`.
`loadLocalEnv` has been removed.
It is now handled by `serverless-offline` a too, and I believe it's the default behaviour.

**Comment by bboure** [comment]
I'll investigate and try to reproduce.

If you have a way to reproduce, please let me know
