### ISSUE TITLE
Update serverless-appsync-plugin to Support Configuration Changes in Version v2

### ISSUE THREAD

**Issue by maher-rddi** [bboure/serverless-appsync-simulator#190]
Hi everyone,

I have upgraded [the serverless-appsync-plugin](https://github.com/sid88in/serverless-appsync-plugin) from version v1 to v2. In version v2, the serverless configuration should be located in the root file instead of under the `custom` section. This package now specifically handles configurations under `custom.appSync`.

Are there any plans to make changes to support the new version?

**Comment by plezan** [comment]
Hi, we are working on it, take a look at the issue #178. There is a PR open that will be merged in the next pre-release
