### ISSUE TITLE
API server start fails when using Fn::GetAtt when Resources are empty

### ISSUE THREAD

**Issue by FilipPyrek** [bboure/serverless-appsync-simulator#20]
**Describe the bug**
I'm passing the AppSync GraphQL API endpoint to functions via intrinsic function in environment variables. It works with no problem when deployed. But when I try running it locally, I get error:
```
AppSync Simulator: TypeError: Cannot read property 'GraphQlApi' of undefined
```

**To Reproduce**
Put into `provider.environment` for examlpe:
```yaml
API_URL: { 'Fn::GetAtt': ['GraphQlApi', 'GraphQLUrl'] }
```
and run `$ serverless offline start`

**Expected behavior**
There should be no error when starting the API server and the value should be taken from `custom.appsync-simulator.getAttMap`.

**Screenshots**
![image](https://user-images.githubusercontent.com/6282843/81557232-e9c59a00-938b-11ea-9788-407288f41ddd.png)

**Additional context**
I figured out that this issue comes from the `cfn-resolver-lib`.
To be exact - from [ResourcesNode.findWrappedResource](https://github.com/robessog/cfn-resolver-lib/blob/master/src/nodeTypes/ResourcesNode.js#L10)

The error disappears when I put some contents into the Resources for example like this:
```yaml
resources:
  Resources:
    abc: def
```
it causes, that `this.wrappedObject` is not `undefined` anymore because [`addChild`](https://github.com/robessog/cfn-resolver-lib/blob/master/src/nodeTypes/ObjectNode.js#L10-L13) method was called on [`ResourcesNode` ](https://github.com/robessog/cfn-resolver-lib/blob/master/src/nodeTypes/ResourcesNode.js) and thus `this.wrappedObj = {}` was performed.

Possible quick solution that comes to my mind is doing something like this in [index.js](https://github.com/bboure/serverless-appsync-simulator/blob/master/src/index.js#L155):
```diff
- Resources: this.serverless.service.resources?.Resources || {},
+ Resources: this.serverless.service.resources?.Resources || { a: 'b' }, 
```
But that's quite ugly solution and I don't really like it.

Any ideas how to properly fix it as easily as possible?

**Comment by bboure** [comment]
@FilipPyrek Can you check if #19  fixes the issue?
I think this is the same issue. It ahs not been release yet though

**Comment by FilipPyrek** [comment]
Unfortunately #19 is not solving this issue at all.

**Comment by FilipPyrek** [comment]
The problem appears when [`node.Resources`](https://github.com/bboure/serverless-appsync-simulator/blob/master/src/index.js#L154-L157
) is an empty object. 
```javascript
    const node = {
      Resources: this.serverless.service.resources?.Resources || {},
      toBeResolved,
    };
```
and when `Fn::GetAtt` is used for example in environment variables.

**Comment by bboure** [comment]
@FilipPyrek sorry, I think I understand the issue better now.

Issue seems to be here https://github.com/robessog/cfn-resolver-lib/blob/master/src/nodeTypes/ObjectNode.js#L7

default should probably be `{}`.

**Comment by FilipPyrek** [comment]
Yes, exactly @bboure . Or at least in our use case.

**Comment by bboure** [comment]
> The problem appears when node.Resources  is an empty object.

Yes, that is because, as you said, `addChild` is never called and https://github.com/robessog/cfn-resolver-lib/blob/68a990808c027a84757a19792e8c7d9b309de992/src/nodeTypes/FnGetAttNode.js#L17 fails. 

AN alternative is to safe-check `wrappedObkect` [here](https://github.com/robessog/cfn-resolver-lib/blob/master/src/nodeTypes/ResourcesNode.js#L10) so that [here](https://github.com/robessog/cfn-resolver-lib/blob/68a990808c027a84757a19792e8c7d9b309de992/src/nodeTypes/FnGetAttNode.js#L17) `resource`is null/undefined

Then [this line](https://github.com/robessog/cfn-resolver-lib/blob/68a990808c027a84757a19792e8c7d9b309de992/src/nodeTypes/FnGetAttNode.js#L35) takes over from the `attrResolvers`.

I guess we could open a PR

**Comment by FilipPyrek** [comment]
If you want, I can open the PR in `cfn-resolver-lib`. Just let me know. 


btw. thanks for such a nice plugin. 👏 Otherwise it would be a mess developing AppSync APIs locally. This solution is much better than unmaintained [serverless-appsync-offline](https://github.com/aheissenberger/serverless-appsync-offline) plugin which depends on Java because of the forced DynamoDB local integration.

**Comment by bboure** [comment]
> If you want, I can open the PR in cfn-resolver-lib. Just let me know.

Feel free to open a PR, I'll back it.
