### ISSUE TITLE
API key is readonly in Amplify GraphQL UI

### ISSUE THREAD

**Issue by FilipPyrek** [bboure/serverless-appsync-simulator#36]
**Describe the bug**
I was trying to change the API key in the Amplify GraphQL UI, but the input is `readonly`. 
So then I need to set as API key, the one from Amplify GraphQL UI

```yml
appsync-simulator:
    apiKey: da2-fakeApiId123456
```

**To Reproduce**
Click on "Update Auth", then try changing the value of the "ApiKey" input.

**Expected behavior**
Hotfix: use the Amplify GraphQL UI key as the default one
Proper fix:  fix it in Amplify GraphQL UI

**Screenshots**
![image](https://user-images.githubusercontent.com/6282843/85045675-96671880-b18f-11ea-83ec-06b8a97f0a4b.png)

**Comment by FilipPyrek** [comment]
I think that changing the default value in this project could do the job nicely. What do you think @bboure ?

**Comment by bboure** [comment]
@FilipPyrek yeah, it would be a breaking change though.
Not a critical one, but still...
I could become frustrating for users that have always used `0123456789`

Or maybe, if some people use the simulator in CI, we would be breaking their builds..

BTW, how do you start the UI ? It seems to have stopped working for me and I  cannot figure out why.

**Comment by FilipPyrek** [comment]
I know it would be a breaking change.. but if we do it properly - according to semantic versioning - and we inform users about this breaking change in some changelog.. they will be well informed and I think it should not be that big deal. 

How do I start the UI? This plugin does it for me, right? I just go to the GraphiQL endpoint address:

README.md:
> ```
> ...
> Serverless: AppSync endpoint: http://localhost:20002/graphql
> Serverless: GraphiQl: http://localhost:20002
> ...
> ```

What do you mean by "stopped working"? Like it doesn't load at all? Or it just doesn't load the schema?
Because I've noticed that before I found this bug, the UI was broken.. because it was sending the schema requests to the API and it got 401 because of the incorrect API key...
But after putting the same key (`da2-fakeApiId123456`) in the sls.yml config, it started to work properly.

**Comment by bboure** [comment]
Never mind, I was getting the following error
`Cannot GET /` 

It seems like I had my local repo pointing to my local dev env of `amplify-cli`
Probably from when I had been working on it recently. I was probably missing some package or something. 
After reinstalling the plugin, it now works.

**Comment by aldegoeij** [comment]
@FilipPyrek where did you add this in serverless.yml? Tried every combo I can think of but can't find the right one :D

**Comment by FilipPyrek** [comment]
@aldegoeij you have to put the `appsync-simulator` configuration to the `custom` field as shown here: https://github.com/bboure/serverless-appsync-simulator#configuration

```yaml
custom:
  appsync-simulator:
    apiKey: da2-fakeApiId123456
```

**Comment by appdatasoft** [comment]
@bboure @FilipPyrek even though I am giving apiKey: da2-fakeApiId123456 in serverless.yml, the apiKey is empty in GraphQL UI. Any idea how to fix this?
![Screenshot (3603)](https://user-images.githubusercontent.com/41810092/114251269-4e4ef780-9955-11eb-914f-89abfa465a30.png)

AppSync Simulator: TypeError: Cannot read property 'path' of undefined
offline: Starting Offline: dev/us-east-1.
offline: Offline [http for lambda] listening on http://localhost:3002
offline: Function names exposed for local invocation by aws-sdk:

{
  "errors": [
    {
      "errorType": "UnauthorizedException",
      "message": "Cannot read property 'defaultAuthenticationType' of undefined"
    }
  ]
}

**Comment by appdatasoft** [comment]
> @FilipPyrek where did you add this in serverless.yml? Tried every combo I can think of but can't find the right one :D

Are you able to figure this out?
