### ISSUE TITLE
Support Direct Lambdas

### ISSUE THREAD

**Issue by bboure** [bboure/serverless-appsync-simulator#45]
See 

https://aws.amazon.com/blogs/mobile/appsync-direct-lambda/
https://github.com/sid88in/serverless-appsync-plugin/issues/348
https://github.com/sid88in/serverless-appsync-plugin/pull/350

Will probably require a change in https://github.com/aws-amplify/amplify-cli

**Comment by Gdewilde** [comment]
Thanks for this plugin! Any ETA for direct lambda support?

**Comment by bboure** [comment]
@Gdewilde I started to look into this a few days ago. It involves some work in https://github.com/aws-amplify/amplify-cli as they don't support it yet.
I am not quite sure how to do it yet, though.

**Comment by bschulz87** [comment]
Is setting request and/or response on a direct Lamba resolved field to null resulting in this error: 
`AppSync Simulator: Error: ENOENT: no such file or directory, ...` related to this issue?

**Comment by bboure** [comment]
Fixed by #62
@bschulz87 To support direct lambda, you need to set request/response template to  `false`
`null`or 'undefined` means default template naming: `Type.field.vtl`
[See documentation](https://github.com/sid88in/serverless-appsync-plugin#configuring-the-plugin)
