### ISSUE TITLE
'selectionSetGraphQL' parameter from context incorrectly contains the 'arguments' 

### ISSUE THREAD

**Issue by parthbond180** [bboure/serverless-appsync-simulator#49]
**Describe the bug**
I have a Lambda Data Source for a query type in the form (from schema file) - 
```
type Query {
    modelQuery(filters: [Filters!], groupingCriteria: [Criteria!]!): [ModelType!]!
}
```
When I start the appsync simulator, I am able to connect to the local AppSync instance and query it using the 'aws-amplify' library where I send in a request of the form - 

```
query{ 
  modelQuery(groupingCriteria: { keyId: "sector" })
  {
    variableA
    variableB  
  }
```

The above query hits the Local Lambda Data Source correctly, but incorrectly passes in the 'arguments' into the 'selectionSetGraphQL' field (from the Invocation payload of the request) (check: https://docs.aws.amazon.com/appsync/latest/devguide/resolver-context-reference.html) - 
`"selectionSetGraphQL": "{keyId: \"sector\"}) {\n  variableA\n  variableB\n}"`

For comparison, the above works correctly in AppSync proper - 
`"selectionSetGraphQL": "{\n  variableA\n  variableB\n}"`

**To Reproduce**

The relevant serverless mapping template config is:
```
      - dataSource: ModelQuery
        type: Query
        field: modelQuery
        request: "modelQuery-request-mapping-template.vtl"
        response: "modelQuery-response-mapping-template.vtl"
```

'modelQuery-request-mapping-template.vtl' VTL file:
```
{
"version": "2017-02-28",
"operation": "Invoke",
"payload": {
"field": "modelQuery",
"arguments":  $utils.toJson($context.arguments),
"selectionSetGraphQL": $utils.toJson($context.info.selectionSetGraphQL)
}
}

```

**Expected behavior**

The selectionSetGraphQL parameter should pass in the value as it is in AWS AppSync with no arguments being included into the selectionSetGraphQL string - 

`"selectionSetGraphQL": "{\n  variableA\n  variableB\n}"`

rather than
`"selectionSetGraphQL": "{keyId: \"sector\"}) {\n  variableA\n  variableB\n}"`

**Screenshots**

**Additional context**

**Comment by parthbond180** [comment]
Hi @bboure any update on this issue?

**Comment by parthbond180** [comment]
ok is there a workaround for this in the meanwhile? this is breaking one of my API's

**Comment by bboure** [comment]
Sorry @parthbond180  
In your lambda, try to find "})" and take only what is after.

```js
const pos = selectionSetGraphQL.indexOf("})");
if (pos >= 0) {
  selectionSetGraphQL = selectionSetGraphQL.substr(pos);
}
``` 

This is a bit hacky but it might work.
I'll try to fix it asap.

**Comment by bboure** [comment]
PR open https://github.com/aws-amplify/amplify-cli/pull/5602

**Comment by parthbond180** [comment]
Hi @bboure it seems AWS have fixed the PR above, is the fix included on your latest releases?

**Comment by bboure** [comment]
@parthbond180 Yes! They accepted my PR! It is now live.
I will upgrade the dependencies on this package too.
