### ISSUE TITLE
Unable to connect to websocket server for subscriptions

### ISSUE THREAD

**Issue by brno32** [bboure/serverless-appsync-simulator#54]
**Describe the bug**
The server appears to run fine, but when trying to connect from my frontend application I'm getting

```
Unhandled Runtime Error
Error: Connection handshake error
```

In my browser console I can see it trying to connect to the wrong websocket port

```
wss://localhost:62222/graphql?header=***
```

**To Reproduce**
Set up the plugin in the serverless file

``` yml
// serverless.yml

appsync-simulator:
  port: 62222
  wsPort: 62223
```

`package.json` with these deps

``` json
"serverless": "^1.60.0",
"serverless-appsync-plugin": "^1.1.2",
"serverless-appsync-simulator": "0.5.0",
"serverless-offline": "^5.12.1",
```

Connect via the `amplify` library (we're using a React app)

``` typescript
import { Amplify } from 'aws-amplify'

export const awsConfig = {
  Auth: {
    // ...
  },
  aws_appsync_graphqlEndpoint: process.env.API_URL,
  // ...
  API: {
    graphql_endpoint: process.env.API_URL,
    // ...
  }
}

Amplify.configure(awsConfig)
```

And simply try and use a subscription somewhere in your frontend

**Expected behavior**
Websockets should connect and not throw errors when trying to use subscriptions

**Screenshots**
<img width="545" alt="Screenshot 2020-10-29 at 12 26 48" src="https://user-images.githubusercontent.com/30541183/97563484-66ecd600-19e3-11eb-9454-bb8d645e0899.png">

**Additional context**
Possibly related issue? https://github.com/aws-amplify/amplify-cli/issues/4264

I've also tried

 * Using the default ports
 * Setting the websocket server to use the same port

It looks to me like amplify simply does not connect to the right port. However I changed the source code to explicitly connect to the ws port and no luck; it throws the same error

**Comment by brno32** [comment]
A colleague and I looked at this more and I suspect it's an issue with the amplify client, not this library or the appsync simulator it's wrapping

**Comment by bboure** [comment]
@brno32 Thanks for opening this issue.
Yes, it is highly probably that the issue comes from `amplify-cli`.

Try to debug around [here](https://github.com/aws-amplify/amplify-cli/blob/f6dac5b6d55867e35b28b1c3eec9a6eeb4e4fbe3/packages/amplify-appsync-simulator/src/server/subscription.ts#L86) and see the value of the port.

**Comment by FilipPyrek** [comment]
@brno32 try to add
```typescript
aws_appsync_dangerously_connect_to_http_endpoint_for_testing: true
```
to the root of your Amplify configuration object.
That worked for me.

Reference:
https://github.com/aws-amplify/amplify-js/blob/main/packages/pubsub/src/Providers/AWSAppSyncRealTimeProvider.ts#L220-L223
https://github.com/aws-amplify/amplify-js/blob/main/packages/pubsub/src/Providers/AWSAppSyncRealTimeProvider.ts#L578

**Comment by brno32** [comment]
Ah nice find! That indeed makes the original error go away, but for me subscriptions still aren't working end-to-end. My client is unable to subscribe. After some time, I get

```
Error in connection establishment: net::ERR_NETWORK_IO_SUSPENDED
```

**Comment by FilipPyrek** [comment]
🤔 Try installing latest version of `aws-amplify` and `serverless-appsync-simulator` @brno32

**Comment by brno32** [comment]
Darn same deal. I upgraded `aws-amplify` to `3.3.10` and `serverless-appsync-simulator` to `0.8.1`
