### ISSUE TITLE
Plugin crashes with a VPC and GetAZs in the stack (Index 0 is out of bound)

### ISSUE THREAD

**Issue by somq** [bboure/serverless-appsync-simulator#55]
**Describe the bug**
`appsync-simulator` does not succeed to launch if a VPC with `GetAZs` attributes is present in the stack.  
The error message is `Index *n* is out of bound.`

**To Reproduce**
Here is a repro repo: https://github.com/somq/appsync-out-of-bound-issue

**Expected behavior**
`cfn-resolver` should be able to parse`GetAZs` & `appsync-simulator` should run and output the graphql URLs.

**Additional context**
I've tried to debug but it is not clear to me where does the issue come from.  
In `Index *n* is out of bound.` `n` corresponds to the index of the AZ array, but `cfn-resolvers` fails to map the region to [its AZ](https://github.com/robessog/cfn-resolver-lib/blob/master/src/AZMap.json) because [`currentRegion`](https://github.com/robessog/cfn-resolver-lib/blob/master/src/nodeTypes/FnGetAZsNode.js#L7) is undefined.

Any help would be appreciated at this point.

**Comment by somq** [comment]
Any update on this one @bboure?

**Comment by bboure** [comment]
Sorry @somq for getting back late to you.
Could you please try the following?

In [this block](https://github.com/bboure/serverless-appsync-simulator/blob/master/src/index.js#L124-L133), add:

```js
'AWS::Region': this.serverless.service.provider.region,
```

and see if this works.

**Comment by somq** [comment]
Thanks for your time, it does fix the issue.  
I made a PR with the change.
