### ISSUE TITLE
Error on @model & @versioned directives in graphql schema

### ISSUE THREAD

**Issue by sarfraaz-talat** [bboure/serverless-appsync-simulator#71]
I am getting this error while trying to run  it

<img width="1332" alt="Screenshot 2021-01-21 at 10 52 16 PM" src="https://user-images.githubusercontent.com/24787560/105387840-f8af5c80-5c3b-11eb-8a4d-366db517c792.png">

I have plugins as below in my serverless.yml

<img width="384" alt="Screenshot 2021-01-21 at 10 57 24 PM" src="https://user-images.githubusercontent.com/24787560/105387931-1086e080-5c3c-11eb-9b2c-3204e4c6554b.png">

Running below command to start

`sls offline start`

**Comment by bboure** [comment]
@sarfraaz-talat What is the purpose of the @model directive in your code?
AFAIK, that directive is related to amplify-cli. It has no effect at all in this serverless plugin.
This is why you are getting the error. 

That being said, we could probably work on ignoring all (unknown) directives as I understand that they might have a purpose for some users.

**Comment by sarfraaz-talat** [comment]
Yes, it is related to amplify-cli. If it could be worked to ignore the unknown directives from schema would be great help. I have to maintain duplicate schema files due to this.

**Comment by bboure** [comment]
@sarfraaz-talat Out of curiosity. Are you using both this plugin and amplify-cli? 
What is your use case? I consider them as alternatives and don't see how they fit together in the same project.
