### ISSUE TITLE
Feature Request: Aurora/Data API Simulation

### ISSUE THREAD

**Issue by wSedlacek** [bboure/serverless-appsync-simulator#75]
**Is your feature request related to a problem? Please describe.**
I am looking to build out an application using App Sync and the Aurora Serverless.
From what I have read in the resolver [tutorial](https://docs.aws.amazon.com/appsync/latest/devguide/tutorial-rds-resolvers.html) the VTL for Aurora Serverless statements is really simple, but it's not clear how this could be run offline.
From what I can tell looking over this library it seems to focus around support for DynamoDB.

**Describe the solution you'd like**
I would like to be able to point at a local MySQL or Postgres database and have the appsync simulator run statements against that. 

**Describe alternatives you've considered**
I am still in the initial investigation of AWS and AppSync in general so I don't personally have a lot of context into this as of yet.
I would love to hear feedback from others on possible solutions to this.

**Comment by bboure** [comment]
Thank you @wSedlacek for this feature request.

Adding support for Aurora would be great. It would be definitely possible to point to a local Mysql/Postgres db.

I do not have any experience using Mysql/PostGres with AppSync (or node.js), though.

The solution is probably to add a [DataLoader](https://github.com/bboure/serverless-appsync-simulator/tree/master/src/data-loaders) for RDS, add a [config](https://github.com/bboure/serverless-appsync-simulator#configuration) for RDS with the following attributes:
- type: mysql/postgres
- endpoint
- user
- password
- database name

**Comment by wSedlacek** [comment]
I'll give it a shot and let you know what happens

**Comment by katesclau** [comment]
Hey, we have the same requirement, I'll also put some effort on this 💪

**Comment by katesclau** [comment]
Seems this was solve by https://github.com/bboure/serverless-appsync-simulator/pull/110
