### ISSUE TITLE
{"statusCode":404,"error":"Not Found","message":"Not Found"}

### ISSUE THREAD

**Issue by appdatasoft** [bboure/serverless-appsync-simulator#87]
**Describe the bug**
{"statusCode":404,"error":"Not Found","message":"Not Found"}
http://localhost:3002

**To Reproduce**
$serverless offline
offline: Starting Offline: dev/us-east-1.
offline: Offline [http for lambda] listening on http://localhost:3002
offline: Function names exposed for local invocation by aws-sdk:

**Expected behavior**
Expecting to not get error

**Screenshots**

**Additional context**

**Comment by muditsunarctech** [comment]
Hey, How did you get this working?
