### ISSUE TITLE
Cannot use the plugin with multiple AppSync APIs

### ISSUE THREAD

**Issue by louislatreille** [bboure/serverless-appsync-simulator#90]
**Describe the bug**
I have a serverless project with multiple AppSync APIs configured.

E.g.
```
custom:
  appSync:
    - name: api-one
       ...
    - name: api-two
       ...
    - name: api-three
       ...
```

When deploying the stack locally with `sls offline start`, I can only make requests against the first API defined in the list. Trying to make requests on other APIs returns an error stating that the operation doesn't exist.
>Cannot query field \"getField\" on type \"Query\"."

**To Reproduce**
1. Create a project with two or more AppSync APIs.
2. Start it with `sls offline start`.
3. Make a request against any API except the first one.

**Expected behavior**
An endpoint (or host on different ports) exist for each AppSync API

**Comment by bboure** [comment]
Hi @louislatreille Thank you for reporting this.
You are correct. For now, [only the first API is supported](https://github.com/bboure/serverless-appsync-simulator/blob/master/src/index.js#L82-L85). This should probably be better documented in the README.

It should be possible to support all APIs by spawning more than one server, each using a different port number. 
If you feel like it, feel free to open a PR and I'd be happy to have a look.

**Comment by louislatreille** [comment]
Thanks @bboure that clarifies the issue! I'll see if I can work on a PR some times. It doesn't seem to complicated to add that functionality.

**Comment by louislatreille** [comment]
@bboure I've opened #92 to address this.
