### ISSUE TITLE
DynamoDB batch operations fail with error 'not implemented'

### ISSUE THREAD

**Issue by etaylor23** [bboure/serverless-appsync-simulator#96]
**Describe the bug**
When invoking a resolver that causes a DynamoDB batch operation on my local serverless API, I receive an error stating 'GraphQL error: Operation  BatchPutItem not implemented'. 

**To Reproduce**
- Create a resolver and mapping template which runs a BatchPutItem request to DynamoDB
- Run the mutation

**Expected behavior**
Inline with how AppSync itself behaves, I'd expect that the BatchPutItem performs as any other DynamoDB operation does, in this case by inserting all appropriate records into the DB

**Screenshots**
N/A

**Additional context**
N/A

**Comment by bboure** [comment]
Thank you @etaylor23 

This is a limitation by [amplify-cli](https://github.com/aws-amplify/amplify-cli/)
As the error says, [BatchPutItem is not implemented](https://github.com/aws-amplify/amplify-cli/blob/master/packages/amplify-appsync-simulator/src/data-loader/dynamo-db/index.ts#L45-L48)

Feel free to open a PR or issue there.

I think there is already some effort being do to implement [Batch](https://github.com/aws-amplify/amplify-cli/pull/5965) and [transaction](https://github.com/aws-amplify/amplify-cli/pull/5965) operation

**Comment by vincent38wargnier** [comment]
So it's not possible to do batch with Amplify?
