### ISSUE TITLE
Watchman:  spawn watchman ENOENT  - 

### ISSUE THREAD

**Issue by appdatasoft** [bboure/serverless-appsync-simulator#97]
I am getting the following error when starting on windows:

Watchman:  spawn watchman ENOENT
 
 Error ---------------------------------------------------

  Error: spawn watchman ENOENT
      at Process.ChildProcess._handle.onexit (internal/child_process.js:269:19)
      at onErrorNT (internal/child_process.js:465:16)
      at processTicksAndRejections (internal/process/task_queues.js:80:21)

Below is the full stack trace:

Serverless: Invoke offline:start
AppSync Simulator: backend-starter-vivekt AppSync endpoint: http://172.20.240.1:20002/graphql
AppSync Simulator: backend-starter-vivekt GraphiQl: http://172.20.240.1:20002
offline: Starting Offline: dev/us-east-1.
[offline] options: {
  allowCache: false,
  apiKey: 'd41d8cd98f00b204e9800998ecf8427e',
  corsAllowCredentials: true,
  corsAllowHeaders: [ 'accept', 'content-type', 'x-api-key', 'authorization' ],
  corsAllowOrigin: [ '*' ],
  corsExposedHeaders: [ 'WWW-Authenticate', 'Server-Authorization' ],
  disableCookieValidation: false,
  dockerHost: 'localhost',
  dockerHostServicePath: null,
  dockerNetwork: null,
  dockerReadOnly: true,
  enforceSecureCookies: false,
  functionCleanupIdleTimeSeconds: 60,
  hideStackTraces: false,
  host: 'localhost',
  httpPort: 4040,
  httpsProtocol: '',
  lambdaPort: 3002,
  layersDir: null,
  noAuth: false,
  noPrependStageInUrl: false,
  noTimeout: false,
  prefix: '',
  printOutput: false,
  resourceRoutes: false,
  useChildProcesses: false,
  useDocker: false,
  useWorkerThreads: false,
  webSocketHardTimeout: 7200,
  webSocketIdleTimeout: 600,
  websocketPort: 3001,
  corsConfig: {
    credentials: true,
    exposedHeaders: [ 'WWW-Authenticate', 'Server-Authorization' ],
    headers: [ 'accept', 'content-type', 'x-api-key', 'authorization' ],
    origin: [ '*' ]
  }
}
Watchman:  spawn watchman ENOENT
 
 Error ---------------------------------------------------

  Error: spawn watchman ENOENT
      at Process.ChildProcess._handle.onexit (internal/child_process.js:269:19)
      at onErrorNT (internal/child_process.js:465:16)
      at processTicksAndRejections (internal/process/task_queues.js:80:21)

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com

  Your Environment Information ---------------------------
     Operating System:          win32
     Node Version:              14.16.1
     Framework Version:         2.40.0
     Plugin Version:            4.5.3
     SDK Version:               4.2.2
     Components Version:        3.9.2

offline: Offline [http for lambda] listening on http://localhost:3002
offline: Function names exposed for local invocation by aws-sdk:
           
        
[offline] Lambda Invocation Routes (for AWS SDK or AWS CLI):
           

   

offline: [HTTP] server ready: http://localhost:4040 🚀
offline:
offline: Enter "rp" to replay the last request
error Command failed with exit code 1.

**Comment by thekamahele** [comment]
Just upgraded to latest and same issue on a mac

**Comment by moioo91120** [comment]
Same thing,
and i noticed I have this 2 lines where Appsync is somehow going to 10.5.3.175, no idea why or what it is :

AppSync Simulator: undefined AppSync endpoint: http://10.5.3.175:20002/graphql
AppSync Simulator: undefined GraphiQl: http://10.5.3.175:20002

**Comment by matmunn** [comment]
This issue is resolved by installing watchman.

From the docs:
> Hot-reloading relies on watchman. Make sure it is installed on your system.

**Comment by Mudassir-23** [comment]
@matmunn thanks! Installing watchman resolved this issue.
Note for people like me who didn't knew what watch is earlier. Watchman is not a npm package. https://facebook.github.io/watchman/docs/install.html

**Comment by matmunn** [comment]
Thanks for posting the link, I should have done that myself.

**Comment by alvaroseparovich** [comment]
Hey, this is the default behavior, as described in the doc, its reasonable to add this to the readme dependencies. Tough this is cleared in this issue, some guys who use the plugin at the first time (as I do) will need to do a bit of search to know what is happening when this problem raises.
